In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("IMDB Dataset.csv")

In [3]:
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
data.drop_duplicates(inplace = True)

In [5]:
data.shape

(49582, 2)

Data Preprocessing

1. Converting to lower case

In [6]:
data["review"] = data["review"].str.lower()

2. Removeing the URLs

In [7]:
import re

def remove_urls(text):
    text = re.sub(r"https\S+", "", text) #patter, replace with, string
    return text

data["review"] = data["review"].apply(remove_urls)

3. Removeing the Punctuations

In [8]:
def remove_punctuations(text):
    text = re.sub(r"[^A-Za-z0-9\s+]","",text)
    return text
data["review"] = data["review"].apply(remove_punctuations)

4. Remove HTML

In [9]:
def remove_HTML(text):
    text = re.sub(r"<.*?>", "", text)
    return text
data["review"] = data["review"].apply(remove_HTML)

5. Removeing the Stopwords

In [10]:
import nltk

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to C:\Users\Krishna
[nltk_data]     Verma\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to C:\Users\Krishna
[nltk_data]     Verma\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\Krishna
[nltk_data]     Verma\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [11]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [13]:
def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")

    for word in tokens:
        if word in stop_words:
            text = text.replace(word,"")
    return text


data["review"] = data["review"].apply(remove_stopwords)

In [15]:
data.head()

                                              review sentiment
0  e    revewers  nted   wtchg  1 oz epode ll  ho...  positive
1   wderful ltle producti br br  filming techniqu...  positive
2   thought ths   wderful wy  spend tme   o hot s...  positive
3  bsclly res  fmly   lttle boy jke thks res  zom...  negative
4  petter mtte love   time  mey   vully stunng fi...  positive

6. Stemming

In [16]:
# running -> run
# played -> play
# This is called porterstemming

from nltk.stem import PorterStemmer

In [18]:
def stemming(text):
    ps = PorterStemmer()
    stemmed_words = []

    tokens = word_tokenize(text)
    for token in tokens:
        stemmed_token = ps.stem(token)
        stemmed_words.append(stemmed_token)
    return " ".join(stemmed_words)


data["review"] = data["review"].apply(stemming)

In [19]:
data.head()

                                              review sentiment
0  e revew nted wtchg 1 oz epod ll hook y rght ex...  positive
1  wder ltle producti br br film techniqu unssum ...  positive
2  thought th wder wy spend tme o hot summer week...  positive
3  bsclli re fmli lttle boy jke thk re zomb close...  negative
4  petter mtte love time mey vulli stunng film wt...  positive

7. Encoding

In [21]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

data["sentiment"] = le.fit_transform(data["sentiment"])

In [25]:
y = data["sentiment"]
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

8. Vectorization

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()

X = tf.fit_transform(data["review"])
X