In [1]:
#KNN

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)


from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [2]:
diabetes = pd.read_csv("diabetes_prediction_dataset.csv")
diabetes.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [3]:
#### THIS DOES'T WORK BECAUSE OF MULTIPLE DATA (MORE THAN TWO)
#diabetes["gender"] = diabetes["gender"].map({"Male":0, "Female":1})
#diabetes.head()

In [4]:
diabetes=pd.get_dummies(diabetes,columns=["gender","smoking_history"],drop_first = True,dtype = int)
diabetes.head()

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes,gender_Male,gender_Other,smoking_history_current,smoking_history_ever,smoking_history_former,smoking_history_never,smoking_history_not current
0,80.0,0,1,25.19,6.6,140,0,0,0,0,0,0,1,0
1,54.0,0,0,27.32,6.6,80,0,0,0,0,0,0,0,0
2,28.0,0,0,27.32,5.7,158,0,1,0,0,0,0,1,0
3,36.0,0,0,23.45,5.0,155,0,0,0,1,0,0,0,0
4,76.0,1,1,20.14,4.8,155,0,1,0,1,0,0,0,0

In [5]:
X = diabetes.drop(columns = ["diabetes"])
Y = diabetes["diabetes"]

In [6]:
# DATA SPLIN INTO TRAIN AND TEST
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size = 0.2, random_state = 42
)

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
knnNeigh = KNeighborsClassifier(n_neighbors = 5)
knnNeigh.fit(X_train, Y_train)

Y_pred = knnNeigh.predict(X_test)

In [9]:
for k in range(1, 21):
    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(X_train, Y_train)

    pred = model.predict(X_test)

    print(k, recall_score(Y_test, pred))

1 0.667447306791569
2 0.5790398126463701
3 0.6334894613583139
4 0.5714285714285714
5 0.6100702576112412
6 0.5649882903981265
7 0.5889929742388759
8 0.5550351288056206
9 0.5755269320843092
10 0.5532786885245902
11 0.5731850117096019
12 0.5468384074941453
13 0.5597189695550351
14 0.5362997658079626
15 0.5509367681498829
16 0.5357142857142857
17 0.5433255269320844
18 0.5322014051522248
19 0.5433255269320844
20 0.5304449648711944

In [14]:
print("Accuracy :", accuracy_score(Y_test, Y_pred))
print("Precision:", precision_score(Y_test, Y_pred))
print("Recall   :", recall_score(Y_test, Y_pred))
print("F1 Score :", f1_score(Y_test, Y_pred))

print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))

Accuracy : 0.9605
Precision: 0.8936535162950258
Recall   : 0.6100702576112412
F1 Score : 0.7251217814892137
[[18168   124]
 [  666  1042]]
              precision    recall  f1-score   support

           0       0.96      0.99      0.98     18292
           1       0.89      0.61      0.73      1708

    accuracy                           0.96     20000
   macro avg       0.93      0.80      0.85     20000
weighted avg       0.96      0.96      0.96     20000